### ISSUE TITLE
Question: Using thumbnails for successfully uploaded images.

### ISSUE THREAD

**Issue by csLiKevin** [Alem/django-jfu#15]

**Comment by CameronSmith93** [comment]
@csLiKevin Would you mind sharing how you solved this?
The solution given by @Alem as you said results in a thumbnail-sized image saved on the server as the actual upload.

I don't see any code in the plugin that is creating a thumbnail to return on success - am I missing something? What is the best way to implement this like the PHP version?

Thanks!

**Comment by andreav** [comment]
+1 
I'm uploading images to Amazon S3, this process takes a long time, and I would avoid some more time spent at creating a thumbnail + saving it to remote storage only for presenting a successfully uploaded thumbnail.
Thanks.

**Comment by kartikdanidhariya** [comment]
@andreav 
hi i also try uploaded image with Amazon S3 but it return internal server error 
"NotImplementedError at /en/upload/
This backend doesn't support absolute paths."
any help please it life saving for me

**Comment by andreav** [comment]
@kartikdanidhariya it seems like you did not implement the upload handler view. But you provided very little information.

**Comment by dzhuang** [comment]
Finally I figured it out.

Create a css file in your static folder, for example `jfu.css`,  which include:

```
/* thumbnail css settings for uploaded images */
.preview img {
    max-height:100px;
}
```

Then, in your template, add the following code:

```
{% block CSS_EXTRA %}
<link rel="stylesheet" href="{{ STATIC_URL }}jfu.css" >
{% endblock %} 
```
