### ISSUE TITLE
How to add args to upload view?

### ISSUE THREAD

**Issue by stelzzz** [Alem/django-jfu#5]
Hello!
How to use JFU for add variable in upload view?
For example, set some keys for YourUploadModel

```
@require_POST
def upload( request, some_key ):
    file = upload_receive( request )

    instance = YourUploadModel( some_key=some_key, sfile_field = file )
    instance.save()
...
```

**Comment by dhruvnarang** [comment]
@stelzzz i was working on the same thing, do you know how to save the data in the database in upload function after retrieval from the template?

**Comment by kartikdanidhariya** [comment]
I tried but not working
